### ISSUE TITLE
 Can't resolve 'stream/web' ./undici/lib/fetch

### ISSUE THREAD

**Issue by ArthurBonsu** [nodejs/undici#1541]
## Logs & Screenshots

./node_modules/hardhat/node_modules/undici/lib/core/util.js
Module not found: Can't resolve 'stream/web' in 'D:\BLOCKCHAIN EXPERIMENTAL LAB\flowstationyarnV2\flowstationyar
n\flowstationkingdom\node_modules\hardhat\node_modules\undici\lib\core'

Import trace for requested module:
./node_modules/hardhat/node_modules/undici/index.js
./node_modules/hardhat/internal/hardhat-network/jsonrpc/server.js
./node_modules/hardhat/builtin-tasks/node.js
./node_modules/hardhat/internal/core/tasks/builtin-tasks.js
./node_modules/hardhat/internal/core/config/config-loading.js
./node_modules/hardhat/internal/lib/hardhat-lib.js
./pages/originaltokenswap.tsx

./node_modules/hardhat/node_modules/undici/lib/fetch/body.js
Module not found: Can't resolve 'util/types' in 'D:\BLOCKCHAIN EXPERIMENTAL LAB\flowstationyarnV2\flowstationyar
n\flowstationkingdom\node_modules\hardhat\node_modules\undici\lib\fetch'

Import trace for requested module:
./node_modules/hardhat/node_modules/undici/lib/fetch/response.js
./node_modules/hardhat/node_modules/undici/index.js
./node_modules/hardhat/internal/hardhat-network/jsonrpc/server.js
./node_modules/hardhat/builtin-tasks/node.js
./node_modules/hardhat/internal/core/tasks/builtin-tasks.js
./node_modules/hardhat/internal/core/config/config-loading.js
./node_modules/hardhat/internal/lib/hardhat-lib.js
./pages/originaltokenswap.tsx

./node_modules/hardhat/node_modules/undici/lib/fetch/body.js
Module not found: Can't resolve 'stream/web' in 'D:\BLOCKCHAIN EXPERIMENTAL LAB\flowstationyarnV2\flowstationyar
n\flowstationkingdom\node_modules\hardhat\node_modules\undici\lib\fetch'

Import trace for requested module:
./node_modules/hardhat/node_modules/undici/lib/fetch/response.js
./node_modules/hardhat/node_modules/undici/index.js
./node_modules/hardhat/internal/hardhat-network/jsonrpc/server.js
./node_modules/hardhat/builtin-tasks/node.js
./node_modules/hardhat/internal/core/tasks/builtin-tasks.js
./node_modules/hardhat/internal/core/config/config-loading.js
./node_modules/hardhat/internal/lib/hardhat-lib.js
./pages/originaltokenswap.tsx

./node_modules/hardhat/node_modules/undici/lib/fetch/index.js
Module not found: Can't resolve 'stream/web' in 'D:\BLOCKCHAIN EXPERIMENTAL LAB\flowstationyarnV2\flowstationyar
n\flowstationkingdom\node_modules\hardhat\node_modules\undici\lib\fetch'

Import trace for requested module:
./node_modules/hardhat/node_modules/undici/index.js
./node_modules/hardhat/internal/hardhat-network/jsonrpc/server.js
./node_modules/hardhat/builtin-tasks/node.js
./node_modules/hardhat/internal/core/tasks/builtin-tasks.js
./node_modules/hardhat/internal/core/config/config-loading.js
./node_modules/hardhat/internal/lib/hardhat-lib.js
./pages/originaltokenswap.tsx

**Comment by ronag** [comment]
Node version?

**Comment by ArthurBonsu** [comment]
Node.js v16.14.0.

**Comment by mcollina** [comment]
+Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by ronag** [comment]
We don't support node 16.4

**Comment by jimmywarting** [comment]
fyi, `stream/web` seems like it was added in 16.5 [#](https://nodejs.org/dist/latest-v18.x/docs/api/webstreams.html#web-streams-api)

**Comment by ArthurBonsu** [comment]
Reproduceable Codebase
https://drive.google.com/file/d/1ia_oq1A2R6TTkGhfRe4qVUheQywTAW0s/view?usp=sharing

**Comment by ArthurBonsu** [comment]
Can I have a list or a link to  compatible node version or the latest
supported version?

**Comment by ArthurBonsu** [comment]
Problem Unresolved

**Comment by WillQizza** [comment]
I'm having this issue on v16.10.0

**Comment by jimmywarting** [comment]
guessing you have a build problem that can't resolve `stream/web` as an built in NodeJS module and so it thinks that it's a NPM module and can't resolve the NPM module.

maybe it something that could have been resolved if undici would have used prefixed `node:stream/web` instead...?

**Comment by ArthurBonsu** [comment]
The problem persists after node: stream/web. I altered the files within
fetch. The problem persists after  build

**Comment by il3ven** [comment]
I had this problem in a typescript project. I was able to solve it using `npm install @types/node`. 

However, I still have a question. This project uses [`stream/web`](https://nodejs.org/docs/latest-v16.x/api/webstreams.html) which is only available for node `>=16`. How is this project compatible with node versions `<=16`? The package.json of this project mentions [`node: >=12.18`](https://github.com/nodejs/undici/blob/main/package.json#L101).

**Comment by jimmywarting** [comment]
> However, I still have a question. This project uses [stream/web](https://nodejs.org/docs/latest-v16.x/api/webstreams.html) which is only available for node >=16. How is this project compatible with node versions <=16? The package.json of this project mentions [node: >=12.18](https://github.com/nodejs/undici/blob/main/package.json#L101).

Only parts of the undici may be supported not all of it. fetch per say require 16+

**Comment by mcollina** [comment]
I would be very happy to receive a PR with a fix for this that includes a unit test.

**Comment by il3ven** [comment]
> I would be very happy to receive a PR with a fix for this that includes a unit test.

I'd be more than happy to contribute but I am not sure if this is a bug in undici. In my case, the problem was with my build process. Nothing to do with undici. I don't know about @ArthurBonsu's (OP) problem.

**Comment by ArthurBonsu** [comment]
As seen from the issue title, build process stops at upon failing to
resolve the package within the undici. This seems like an internal issue
within undici package. This affects all entire process especially when
using with hardhat modules. Issue must be resolved.

**Comment by jimmywarting** [comment]
i think the issue is with hardhat...

**Comment by fortaleo** [comment]
> npm install @types/node

Thank you! That resolved my issue!
