### ISSUE TITLE
"ReferenceError: AbortSignal is not defined" during jest execution

### ISSUE THREAD

**Issue by JacopoPatroclo** [nodejs/undici#1557]
## Bug Description

When I try to run with jest a test suite that uses a file that import `undici` I get this error

    ReferenceError: AbortSignal is not defined

      at Object.<anonymous> (../node_modules/undici/lib/fetch/request.js:839:3)
      at Object.<anonymous> (../node_modules/undici/index.js:94:28)

## Reproducible By

Create a basic jest configuration with `testEnvironment: 'node',`
Create a js file that imports the `undici` library
Create a spec file to test somthing exported from that file
Run jest

## Expected Behavior

To not throw that exception

## Environment

Node v16.14.0
Jest v27.2.1

### Additional context

Googling the error I found out that another lib had to solve a [similar issue](https://github.com/isaacs/node-lru-cache/issues/239). They think it's related on how jest is mocking AbortSignal and AbortController.

**Comment by ronag** [comment]
Feels more like a jest issue

**Comment by mcollina** [comment]
We are also running some jest tests to verify compatibility, so this is a bit unexpected. There is likely something else at play.

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by watson** [comment]
Odd, I'm getting this issue in a just test suite while upgrading to the newest version of undici. I know it's not the fault of undici, but just thought I'd mention it in this issue in case anybody had found the culprit since this issue was closed.

**Comment by feugy** [comment]
In case this helps, the regression started with version 5.6.0. Working with 5.5.1 works. Trying to assemble a reproduction case.

**Comment by mcollina** [comment]
A PR would be helpful.

**Comment by LaurentZuijdwijk** [comment]
Still no solution for this? I imagine this breaking a lot of projects and it prevents adoption within my organisation.

**Comment by mcollina** [comment]
@LaurentZuijdwijk would you like to send a PR?

**Comment by noel-dolan** [comment]
Also seeing this by simply adding @fastify/http-proxy to project, jest test then start failing:

ReferenceError: AbortSignal is not defined
        at Object.<anonymous> (/Users/ND/development/nebula/_temp/chive/node_modules/undici/lib/fetch/request.js:890:3)
        at Runtime._execModule (/Users/ND/development/nebula/_temp/chive/node_modules/jest-runtime/build/index.js:1299:24)


version info:
node: v16.17.1
package.json bits
...
@fastify/autoload: "^5.0.0",
@fastify/http-proxy: "7.0.0",
axios: "^0.27.2",
fastify: "^4.2.0",
jest: "^26.6.3
...


yarn.lock


undici@^5.0.0:
  version "5.12.0"
  resolved "https://registry.yarnpkg.com/undici/-/undici-5.12.0.tgz#c758ffa704fbcd40d506e4948860ccaf4099f531"
  integrity sha512-zMLamCG62PGjd9HHMpo05bSLvvwWOZgGeiWlN/vlqu3+lRo3elxktVGEyLMX+IO7c2eflLjcW74AlkhEZm15mg==
  dependencies:
    busboy "^1.6.0"

**Comment by noel-dolan** [comment]
Also seeing this by simply adding @fastify/http-proxy to project, jest test then start failing:

ReferenceError: AbortSignal is not defined
        at Object.<anonymous> (/.../node_modules/undici/lib/fetch/request.js:890:3)
        at Runtime._execModule (/.../node_modules/jest-runtime/build/index.js:1299:24)


version info:
node: v16.17.1
package.json bits
...
@fastify/autoload: "^5.0.0",
@fastify/http-proxy: "7.0.0",
axios: "^0.27.2",
fastify: "^4.2.0",
jest: "^26.6.3
...


yarn.lock

**Comment by noel-dolan** [comment]
As mentioned, similar issue seems to have been fixed in another library.

For reference, see: https://github.com/isaacs/node-lru-cache/issues/239

**Comment by dios-david** [comment]
fyi I updated to latest jest (29) and undici works without any issues with the `node` test environment

**Comment by jltxwesley** [comment]
> fyi I updated to latest jest (29) and undici works fine with the `node` test environment

@dios-david No luck with this, having the latest jest (29.3.1) & undici (5.14.0) still throws the ReferenceError

**Comment by dios-david** [comment]
@jltxwesley versions I'm using (from lock file) are:
- `jest 29.2.2`
- `undici 5.12.0`

In the jest config I use `testEnvironment: 'node'`

**Comment by cefeboru** [comment]
Any workaround for this? 

I tried assigning the global AbortSignal on a setup file but more errors keep showing:

```bash
ReferenceError: Event is not defined

      at Object.<anonymous> (node_modules/undici/lib/fileapi/progressevent.js:10:29)
      at Object.<anonymous> (node_modules/undici/lib/fileapi/util.js:10:27)
      at Object.<anonymous> (node_modules/undici/lib/fileapi/filereader.js:7:5)
      at Object.<anonymous> (node_modules/undici/index.js:118:31)
```
And If try to define Event, then:
```bash
ReferenceError: EventTarget is not defined

      at Object.<anonymous> (node_modules/undici/lib/fileapi/filereader.js:18:26)
      at Object.<anonymous> (node_modules/undici/index.js:118:31)
      at Object.<anonymous> (node_modules/@elastic/transport/src/connection/UndiciConnection.ts:36:1)
      at Object.<anonymous> (node_modules/@elastic/transport/src/connection/index.ts:22:1)\
```

I'm using jest 26.2.2 and I can't really upgrade to version 29 as there are hundreds of unit tests and a lot of them break after upgrading.

**Comment by metcoder95** [comment]
Which version of `node` are you using?

**Comment by zabdalimov** [comment]
Had the same issue when using jest v26, resolved it by upgrading jest to v27.

**Comment by paneq** [comment]
Had the same issue when using jest 27.3.1, updating to 27.5.1 helped.

**Comment by ronag** [comment]
sounds like updating to latest jest is  the solution
