### ISSUE TITLE
Z_DATA_ERROR when fetching a "Content-Encoding: gzip, deflate" response from the server

### ISSUE THREAD

**Issue by kettanaito** [nodejs/undici#3762]
## Bug Description

`fetch` is terminated with a `Z_DATA_ERROR` when fetching a `gzip, deflate` compressed response from the server.

## Reproducible By

Here's a 0 dependency reproduction:

1. https://github.com/kettanaito/undici-gzip-deflate
2. `node ./index.js`

Here's a copy-pastable reproduction:

```js
import http from 'node:http'
import zlib from 'node:zlib'

const server = new http.Server((req, res) => {
  res.setHeader('content-encoding', 'gzip, deflate')
  res.end(zlib.deflateSync(zlib.gzipSync('hello world')))
})

server.listen(56789, async () => {
  const response = await fetch('http://localhost:56789/', {
    headers: { 'accept-encoding': 'gzip, deflate' },
  })
  const text = await response.text()
  console.assert(text === 'hello world')
})
```

## Expected Behavior

1. Fetch happens without errors.
2. `await response.text()` returns a decompressed response string `'hello world'`.

## Logs & Screenshots

```
node:internal/deps/undici/undici:11190
            fetchParams.controller.controller.error(new TypeError("terminated", {
                                                    ^

TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:11190:53)
    at Fetch.emit (node:events:517:28)
    at Fetch.terminate (node:internal/deps/undici/undici:10375:14)
    at fetchParams.controller.resume (node:internal/deps/undici/undici:11167:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: incorrect header check
      at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
    errno: -3,
    code: 'Z_DATA_ERROR'
  }
}

Node.js v18.20.3
```

## Environment

Reproducible on all versions of Node:

- 18.20.3
- 20.11.0
- 22.3.0
- 23.0.0

**Comment by Uzlopak** [comment]
isnt this alread fixed in #3632

**Comment by kettanaito** [comment]
@Uzlopak, still reproducible on v23.0.0. Do you have an exact Node.js version where that fix has been merged?

**Comment by Uzlopak** [comment]
I backported it manually. https://github.com/nodejs/undici/pull/3700

Use undici 6.20.0 directly

**Comment by tsctx** [comment]
Sorry, I forgot to backport #3343 to 6.x, this should fix it.

**Comment by tsctx** [comment]
Fixed by #3764
